# 0: Trace, 1: Debug, 2: Error
log: 1

infer:
  map: beginner

train:
  map: beginner
  should_resume: False
  should_save: False
  should_compile: False
  collector:
    # TODO: Change to 500
    frames_per_batch: 150
    batches: 2
  optim:
    lr: 0.00025
    eps: 0.000001
    weight_decay: 0.0
    max_grad_norm: 0.5
    anneal_lr: True
  loss:
    mini_batches_per_batch: 4
    gamma: 0.99
    ppo_epochs: 3
    gae_lambda: 0.95
    clip_epsilon: 0.1
    anneal_clip_epsilon: True
    critic_coef: 1.0
    entropy_coef: 0.01
    loss_critic_type: l2

model:
  results_dir: results
  img_size: 500

env:
  name: SurfChan
  game_speed: 2.0
  steps_per_second: 12
  seconds_to_finish: 6

css:
  close_on_script_close: True

server:
  host: 127.0.0.1
  port: 27015
  close_on_script_close: True

maps:
  beginner:
    start_angle: 90.0
    start: [-128.0, 0.0, 372.0]
    finish: [-140, 2008, -376]
    ground: -424.0
