model:
  bot_count: 1

css:
  path: C:\Games\steamapps\common\Counter-Strike Source
  close_on_script_close: True

server:
  host: 127.0.0.1
  port: 27015
  close_on_script_close: True

maps:
  beginner:
    start: [0, 336, -128]
