map: "beginner"

model:
  img_size: 500

css:
  path: C:\[PATH_TO_STEAM]\steamapps\common\Counter-Strike Source
  close_on_script_close: True

server:
  host: 127.0.0.1
  port: 27015
  close_on_script_close: True

maps:
  beginner:
    start: [-128.0, 0.0, 372.0, 90.0]
    finish: [
      [-232, 2008, -152], [-24, 2008, -152],
      [-232, 2008, -376], [-24, 2008, -376]
    ]
