# 0: Trace, 1: Debug, 2: Error
log: 1

infer:
  map: beginner

train:
  map: beginner
  lr: 0.0003

model:
  img_size: 500

env:
  name: SurfChan

game:
  no_ai: False

css:
  path: C:\[PATH_TO_STEAM]\steamapps\common\Counter-Strike Source
  close_on_script_close: True

server:
  host: 127.0.0.1
  port: 27015
  close_on_script_close: True

maps:
  beginner:
    start_angle: 90.0
    start: [-128.0, 0.0, 372.0]
    finish: [-140, 2008, -376]
